version: "3"
services:
  app:
    container_name: nest-mail-service
    restart: "always"
    build: .
    ports:
      - "9001:9000"
    links:
      - mongo
      - redis
    networks: 
      - backend
  
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27020:27017"
    networks: 
      - backend
    environment:
      - MONGODB_DATABASE=mails

  redis:
    image: "bitnami/redis"
    container_name: redis
    ports:
      - "6380:6379"
    networks: 
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

networks: 
  backend:
    driver: "bridge"
