version: "3"
services:
  app:
    container_name: nest-mail-service
    restart: "always"
    build: .
    ports:
      - "9001:9000"
    links:
      - mongo
    networks: 
      - backend
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27020:27017"
    networks: 
      - backend
    environment:
      - MONGODB_DATABASE=mails

networks: 
  backend:
    driver: "bridge"
